version = 5.3.1
archive_dir = /etc/letsencrypt/archive/mm.publicvm.com
cert = /etc/letsencrypt/live/mm.publicvm.com/cert.pem
privkey = /etc/letsencrypt/live/mm.publicvm.com/privkey.pem
chain = /etc/letsencrypt/live/mm.publicvm.com/chain.pem
fullchain = /etc/letsencrypt/live/mm.publicvm.com/fullchain.pem
[renewalparams]
account = 3f465adfea16756002767dff136927aa
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
mm.publicvm.com = /var/www/certbot
www.mm.publicvm.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-03-04T03:59:09
